language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t abdou/docker-react-travis-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true abdou/docker-react-travis-aws npm run test -- --coverage
