language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t abdou/docker-react-travis-aws -f Dockerfile.dev .

script:
  - echo "haha"

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-228174808256"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
